"""Leak check for personal names / phones / emails in everything under reports/ (CSV + Markdown) and docs/.

  python -m src.leak_check          report only (exit code 1 if anything is found)
  python -m src.leak_check --fix    also scrub description-like cells in Markdown tables in place (CSVs are regenerated by the report commands)

Checks: (1) email and phone patterns anywhere, (2) description-like cells (description, case_name, project_name, folder_description, name) are run
through the scrubber and must not change. The scrub is heuristic, so a clean result means "nothing the scrubber recognises", not a guarantee.
"""
from __future__ import annotations
import csv
import re
import sys
from pathlib import Path

from src import config as cfgmod
from src.schema import connect
from src.scrub_pipeline import build_scrubber
from src.scrub_text import EMAIL, PHONE

TEXT_COLS = {"description", "case_name", "project_name", "folder_description", "name", "description_of_work", "permit_class_desc"}


def _md_tables(lines: list[str]):
    """Yield (header_cells, start_index, end_index) for each Markdown table."""
    i = 0
    while i < len(lines):
        if lines[i].lstrip().startswith("|") and i + 1 < len(lines) and re.match(r"^\s*\|[\s:|-]+\|\s*$", lines[i + 1]):
            j = i + 2
            while j < len(lines) and lines[j].lstrip().startswith("|"):
                j += 1
            yield [c.strip().lower() for c in lines[i].strip().strip("|").split("|")], i, j
            i = j
        else:
            i += 1


def _split(row: str) -> list[str]:
    return [c for c in re.split(r"(?<!\\)\|", row.strip().strip("|"))]


def check(fix: bool = False) -> dict:
    con = connect(cfgmod.DB_PATH); sc = build_scrubber(con)
    root = cfgmod.ROOT
    found: dict[str, list[str]] = {}
    files = sorted((root / "reports").glob("*")) + sorted((root.parent / "docs").glob("*.md")) + [root / "HANDOVER.md", root / "README.md"]
    for f in files:
        if not f.exists() or f.suffix not in (".csv", ".md"):
            continue
        hits: list[str] = []
        if f.suffix == ".csv":
            with open(f, newline="", encoding="utf-8") as fh:
                rows = list(csv.reader(fh))
            if not rows:
                continue
            head = [h.strip().lower() for h in rows[0]]
            tcols = [i for i, h in enumerate(head) if h in TEXT_COLS]
            texts = [(ri, ci, r[ci]) for ri, r in enumerate(rows[1:], 1) for ci in tcols if ci < len(r) and r[ci]]
            for (ri, ci, t), (clean, n) in zip(texts, sc.scrub_many([t for _, _, t in texts])):
                if n and clean != t:
                    hits.append(f"row {ri} col {head[ci]}: scrubber would still remove {n}")
            for ri, r in enumerate(rows[1:], 1):
                for ci, cell in enumerate(r):
                    if EMAIL.search(cell) or PHONE.search(cell):
                        hits.append(f"row {ri} col {head[ci] if ci < len(head) else ci}: email/phone pattern")
        else:
            lines = f.read_text().split("\n"); changed = False
            for header, i, j in _md_tables(lines):
                tcols = [k for k, h in enumerate(header) if h in TEXT_COLS]
                for li in range(i + 2, j):
                    cells = _split(lines[li])
                    texts = [(k, cells[k].strip()) for k in tcols if k < len(cells) and cells[k].strip()]
                    for (k, t), (clean, n) in zip(texts, sc.scrub_many([t for _, t in texts])):
                        if n and clean != t:
                            hits.append(f"line {li + 1} col {header[k]}: scrubber would still remove {n}")
                            if fix:
                                cells[k] = " " + clean.replace("|", "\\|") + " "; changed = True
                    if fix and changed:
                        lines[li] = "|" + "|".join(cells) + "|"
            for li, line in enumerate(lines, 1):
                if EMAIL.search(line) or PHONE.search(line):
                    hits.append(f"line {li}: email/phone pattern")
                    if fix:
                        lines[li - 1] = PHONE.sub("[CONTACT]", EMAIL.sub("[CONTACT]", line)); changed = True
            if fix and changed:
                f.write_text("\n".join(lines))
        if hits:
            found[str(f.relative_to(root.parent))] = hits
    return found


if __name__ == "__main__":
    res = check(fix="--fix" in sys.argv)
    for f, h in res.items():
        print(f"{f}: {len(h)} finding(s)"); [print("   ", x) for x in h[:5]]
    print("files with findings:", len(res), "| total findings:", sum(len(v) for v in res.values()))
    sys.exit(1 if res else 0)
